ArgumentError: no time information in ""
When polling AWS for stack creation events, something's coming back without a time field,
which breaks the sort and causes poll_stack, in lib/command_module/base.rb, to enter its
rescue clause, and eventually fail.